version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_hub
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
